# ref: https://github.com/ublue-os/image-template/blob/main/Containerfile
# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS ctx
COPY silverblue-main-hardened /

# Base Image
FROM ghcr.io/secureblue/cosmic-nvidia-hardened:latest

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/build.sh && \
    ostree container commit

### LINTING
## Verify final image and contents are correct.
RUN bootc container lint --skip etc-usretc
