name: Build and publish a container image

permissions: {}

on:
  workflow_call:
    inputs:
      image-name:
        type: string
        required: true
      containerfile:
        type: string
        required: true
      context:
        type: string
        required: true
      platform:
        type: string
        required: true
      slsa-verify-source:
        type: string
        required: false
        default: ''
    secrets:
      SIGNING_SECRET:
        required: true

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    outputs:
      FULL_IMAGE_REF: ${{ steps.build.outputs.full-image-ref }}
      IMAGE_DIGEST: ${{ steps.build.outputs.image-digest }}
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2

    - name: Build and Push Image
      id: build
      uses: MArpogaus/image-builder-action@20645aa556fe92f8ceeefbfb2eb97202cc176775  # v1.3.0
      with:
        image-name: ${{ inputs.image-name }}
        containerfile: ${{ inputs.containerfile }}
        context: ${{ inputs.context }}
        platform: ${{ inputs.platform }}
        slsa-verify-source: ${{ inputs.slsa-verify-source }}
        signing-secret: ${{ secrets.SIGNING_SECRET }}

  provenance:
    needs: [build_and_push_image]
    permissions:
      actions: read
      id-token: write
      packages: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    with:
      image: ${{ needs.build_and_push_image.outputs.FULL_IMAGE_REF }}
      digest: ${{ needs.build_and_push_image.outputs.IMAGE_DIGEST }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
