name: Build and publish all container images

on:
  schedule:
  - cron: 0 7 * * *
  push:
    branches: [main, dev]
    # Publish semver tags as releases.
    tags: [v*.*.*]
     # don't rebuild if only documentation has changed
    paths-ignore: ['**.md']
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  secureblue-images:
    name: Build and push secureblue container images
    permissions:
      contents: read
      actions: read
      packages: write
      id-token: write
    strategy:
      matrix:
        include:
        - image-name: cosmic-main-hardened
          extra-packages: ''
        - image-name: cosmic-nvidia-hardened
          extra-packages: ''
        - image-name: kinoite-main-hardened
          extra-packages: krdp
        - image-name: kinoite-nvidia-hardened
          extra-packages: krdp
        - image-name: silverblue-main-hardened
          extra-packages: gnome-remote-desktop
        - image-name: silverblue-nvidia-hardened
          extra-packages: gnome-remote-desktop
      fail-fast: false
    uses: ./.github/workflows/build-and-publish-one-image.yml
    with:
      image-name: ${{ matrix.image-name }}
      containerfile: ./containerfiles/base.containerfile
      context: ./context
      platform: linux/amd64
      build-args: |
        BASE_IMAGE=ghcr.io/secureblue/${{ matrix.image-name }}:latest
        EXTRA_PACKAGES=${{ matrix.extra-packages }}
      slsa-verify-source: github.com/secureblue/secureblue
      cosign-public-key: https://raw.githubusercontent.com/secureblue/secureblue/refs/heads/live/cosign.pub
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
