# Inspired by: https://github.com/secureblue/secureblue/blob/live/.github/workflows/iso.yml

name: Build ISOs

permissions: {}

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    name: Build ISOs
    runs-on: ubuntu-24.04
    permissions:
      contents: read # read repo contents
      packages: read # pull images for iso generation
      #id-token: write # generate token for signing
    strategy:
      matrix:
        image:
        - silverblue-main-hardened
        - silverblue-nvidia-hardened
      fail-fast: false

    steps:
      # https://github.com/macbre/push-to-ghcr/issues/12
    - name: Lowercase Registry
      id: registry_case
      uses: ASzc/change-string-case-action@ecd1412d078f2e06e9eedcbaa6fcd988151c3f82 # v8
      with:
        string: ${{ env.REGISTRY }}

    - name: Maximize build space
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
        tool-cache: true

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: false
        swap-storage: true

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Build ISO
      uses: jasonn3/build-container-installer@c9ef3de33236e66781ec37bd0485e8009eaefe24   # v1.4.0
      id: iso_build
      env:
        IMAGE_NAME: ${{ matrix.image }}
      with:
        arch: x86_64
        image_name: ${{ env.IMAGE_NAME }}
        image_repo: ${{ steps.registry_case.outputs.lowercase }}
        image_tag: latest
        version: 43
        variant: Kinoite
        iso_name: ${{ env.IMAGE_NAME }}.iso
        enrollment_password: secureblue
        secure_boot_key_url: https://github.com/secureblue/secureblue/raw/refs/heads/live/files/system/etc/pki/akmods/certs/akmods-secureblue.der
        repos: /etc/yum.repos.d/fedora.repo /etc/yum.repos.d/fedora-updates.repo

    - name: Rename ISO
      id: rename
      shell: bash
      env:
        IMAGE_NAME: ${{ matrix.image }}
        ISO_SIGNING_KEY: ${{ secrets.ISO_SIGNING_KEY }}
      run: |
        sudo chown $(whoami) "${IMAGE_NAME}.iso" "${IMAGE_NAME}.iso-CHECKSUM"

        TARGET_OUTPUT_DIRECTORY="$(pwd)/output"
        mkdir "${TARGET_OUTPUT_DIRECTORY}"
        PREFIX="secureblue"
        DATE_SUFFIX="$(date +%Y%m%d)"
        ISO_NAME="${PREFIX}-${IMAGE_NAME}-${DATE_SUFFIX}.iso"
        CHECKSUM_NAME="${ISO_NAME}-CHECKSUM"
        mv "${IMAGE_NAME}.iso" "${ISO_NAME}"
        mv "${IMAGE_NAME}.iso-CHECKSUM" "${CHECKSUM_NAME}"
        mv "${ISO_NAME}" "$TARGET_OUTPUT_DIRECTORY"
        mv "${CHECKSUM_NAME}" "$TARGET_OUTPUT_DIRECTORY"
        # cd "$TARGET_OUTPUT_DIRECTORY"
        # TODO: Sign CHECKSUM

        echo "output-directory=${TARGET_OUTPUT_DIRECTORY}" >> ${GITHUB_OUTPUT}

    - name: Upload ISO and Checksum to Job Artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        path: ${{ steps.rename.outputs.output-directory }}
        name: ${{ matrix.image }}
        if-no-files-found: error
        retention-days: 3
        compression-level: 0
        overwrite: true
