# Inspired by: https://github.com/secureblue/secureblue/blob/live/.github/workflows/iso.yml

name: Build ISOs

permissions: {}

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    name: Build ISOs
    runs-on: ubuntu-24.04
    permissions:
      contents: read # read repo contents
      packages: read # pull images for iso generation
      #id-token: write # generate token for signing
    strategy:
      matrix:
        image:
        - silverblue-main-hardened
        - silverblue-nvidia-hardened
      fail-fast: false

    steps:
    # https://github.com/macbre/push-to-ghcr/issues/12
    - name: Lowercase Registry
      id: registry_case
      uses: ASzc/change-string-case-action@ecd1412d078f2e06e9eedcbaa6fcd988151c3f82 # v8
      with:
        string: ${{ env.REGISTRY }}
  
    - name: Maximize build space
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
        tool-cache: true
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: false
        swap-storage: true

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Build ISO
      id: build
      uses: ublue-os/titanoboa@840217d97bd0bc9a52466508c54d8dda5c5ba2fd # v0.2
      with:
        image-ref: ${{ steps.registry_case.outputs.lowercase }}/${{ matrix.image }}:latest
        
    - name: Rename ISO
      id: rename
      shell: bash
      env:
        IMAGE_NAME: Fedora-${{ matrix.image }}.iso
      run: |
        mkdir -p output
        mv ${{ steps.build.outputs.iso-dest }} output/$IMAGE_NAME
        (cd output && sha256sum $IMAGE_NAME | tee $IMAGE_NAME-CHECKSUM)

    - name: Upload ISO and Checksum to Job Artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        path: output/
        name: ${{ matrix.image }}
        if-no-files-found: error
        retention-days: 3
        compression-level: 0
        overwrite: true
